api-version: 0.1.0

spring:
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:create.sql';
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
  task:
    scheduling:
      pool:
        size: 2