api-version: 0.0.1

spring:
  datasource:
      driver-class-name: org.h2.Driver
      platform: org.hibernate.dialect.H2Dialect
      url: jdbc:h2:mem:testdb
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
